#!/usr/bin/env python3
r"""
Generate the CASE III overlay drawings (v1.3-beta41) for the TOWER + LSO tabs.

Corrected to the user's CASE III walkthrough:

  TOWER t3*  — marshal-holding OVERHEAD, ZOOMED to the marshal band (15..30 nm,
               boat off-screen up).  A holding RACETRACK on the FB-reciprocal
               radial: commence point at 21 DME / angels 6 (inbound/upwind leg),
               ~5 nm legs (1 min @ 300 kt), left-hand pattern.
  LSO   l3*   — final-approach OVERHEAD (boat right = trap, centreline astern):
               10 nm (level 1200') -> 8 DIRTY UP -> 6 BULLSEYE/NEEDLES ->
               3 TIPOVER (ride glideslope) -> 3/4 CALL THE BALL -> trap.

Hook-gated (shown only when carrier.recoveryCase == 'III').  Splices into
carrier-gui.dlg between the "CASE III OVERLAYS" marker and "SHARED STATUS".
"""
import math
import re
from pathlib import Path

DLG = Path(r"C:\Users\Fett\Saved Games\Claude Dump\CarrierGUI\Hooks\carrier-gui.dlg")

lines = []
def L(s=''): lines.append(s)
def solid(n, x, y, w, h, skin, z): L(f'c.{n} = solidW({round(x)}, {round(y)}, {round(w)}, {round(h)}, {skin}, {z})')
def label(n, t, x, y, w, skin, h): L(f'c.{n} = lbl("{t}", {round(x)}, {round(y)}, {w}, {skin}, {h})')

def arc(prefix, cx, cy, r, a0, a1, n, d=4, skin='SCOPE_RG_SKIN'):
    for i in range(n):
        a = math.radians(a0 + (a1 - a0) * i / (n - 1))
        solid(f'{prefix}{i+1}', cx + r*math.cos(a) - d/2, cy + r*math.sin(a) - d/2, d, d, skin, 3)

L('-- == CASE III OVERLAYS ==  (generated by Tools/gen_case3.py)')
L('-- Overhead drawings shown only when recovery case == III (hook-gated).')
L('')

# ---- TOWER: marshal-holding OVERHEAD, zoomed 15..30 nm ----------------------
TCX = 143                         # radial centreline x
TY0, TY1 = 58, 294                # DME 15 (top) .. DME 30 (bottom)
def tdme(d): return TY0 + (d - 15) * (TY1 - TY0) / 15.0
L('-- TOWER CASE III: marshal-holding overhead (15..30 nm; boat off-screen up)')
label('t3Hdr', "MARSHAL HOLDING  .  radial / DME", 6, 30, 300, 'CapSkin', 14)
solid('t3Rad', TCX, TY0, 1, TY1 - TY0, 'SCOPE_LN_SKIN', 2)              # FB-recip radial
label('t3Boat', "^ BOAT  (15 nm)", TCX - 44, TY0 - 2, 110, 'CarrierMark', 12)
for k, dme in enumerate((15, 20, 25, 30), start=1):
    solid(f't3GR{k}', TCX - 16, tdme(dme), 32, 1, 'SCOPE_LN_SKIN', 2)
    label(f't3LR{k}', f"{dme}", TCX + 20, tdme(dme) - 7, 26, 'RadarLbl', 12)
# holding racetrack: inbound leg on the radial (26 -> 21 DME), outbound leg to
# port, 180 turns at each end.  Commence = 21 DME on the inbound (upwind) leg.
yC, yO = tdme(21), tdme(26)       # commence (top) .. outbound end (bottom)
xIn, xOut = TCX, TCX - 48
solid('t3RtIn',  xIn,  yC, 1, yO - yC, 'SCOPE_RG_SKIN', 3)
solid('t3RtOut', xOut, yC, 1, yO - yC, 'SCOPE_RG_SKIN', 3)
arc('t3RtT', (xIn + xOut) / 2, yC, (xIn - xOut) / 2, -180, 0, 7)        # top turn (at commence)
arc('t3RtB', (xIn + xOut) / 2, yO, (xIn - xOut) / 2,  180, 0, 7)        # bottom turn
solid('t3Comm', xIn - 4, yC - 4, 8, 8, 'CONTACT_SKIN', 4)              # commence point
label('t3CommL', "COMMENCE 21/6k", xIn + 8, yC - 7, 110, 'DeckHdr', 12)
label('t3MarshL', "MARSHAL", xOut - 4, yO + 4, 70, 'DeckSkin', 12)
L('')

# ---- LSO: final-approach OVERHEAD (boat right, centreline astern) -----------
LBX = 498                         # boat x (trap, right)
LX10 = 44                         # 10 nm x (left)
LCY = 150                         # centreline y
def lnm(nm): return LBX - nm * (LBX - LX10) / 10.0
L('-- LSO CASE III: final-approach overhead (boat right; gates 10/8/6/3/0.75)')
label('l3Hdr', "CASE III APPROACH  .  final bearing", 6, 30, 520, 'LabelSkin', 18)
solid('l3CL', LX10, LCY, LBX - LX10, 1, 'SCOPE_RG_SKIN', 3)
solid('l3Boat', LBX - 4, LCY - 5, 14, 10, 'SHIP_MARK_SKIN', 4)
label('l3Cv', "CV", LBX - 2, LCY - 20, 30, 'CarrierMark', 14)
GATES = [(0.75, "3/4", "CALL BALL", 'DeckHdr'),
         (3,    "3",   "TIPOVER / GS", 'DeckHdr'),
         (6,    "6",   "BULLSEYE/NDLS", 'DeckSkin'),
         (8,    "8",   "DIRTY UP", 'DeckSkin'),
         (10,   "10",  "LEVEL 1200", 'DeckSkin')]
for k, (nm, num, txt, sk) in enumerate(GATES, start=1):
    x = lnm(nm)
    solid(f'l3GD{k}', x, LCY - 16, 1, 32, 'SCOPE_LN_SKIN', 2)
    label(f'l3LN{k}', num, x - 6, LCY - 32, 28, 'RadarLbl', 12)
    label(f'l3LD{k}', txt, x - 8, LCY + 20, 110, sk, 13)
label('l3LblD', "nm to go", LX10, LCY - 50, 70, 'RadarLbl', 12)
L('')

new_section = '\n'.join(lines) + '\n'
src = DLG.read_text(encoding='utf-8')
start = re.search(r'-- ?=+ ?CASE III OVERLAYS[^\n]*\n', src)
end = re.search(r'-- ?=+ ?SHARED STATUS', src)
assert end, 'SHARED STATUS marker not found'
if start:
    src = src[:start.start()] + new_section + '\n' + src[end.start():]
else:
    src = src[:end.start()] + new_section + '\n' + src[end.start():]
DLG.write_text(src, encoding='utf-8')
print("CASE III overlays regenerated (zoom 15-30nm racetrack + corrected LSO gates).")
print("  TOWER t3*: t3Hdr,t3Boat,t3Rad,t3GR1-4,t3LR1-4,t3RtIn,t3RtOut,t3RtT1-7,t3RtB1-7,t3Comm,t3CommL,t3MarshL")
print("  LSO   l3*: l3Hdr,l3CL,l3Boat,l3Cv,l3GD1-5,l3LN1-5,l3LD1-5,l3LblD")
