#!/usr/bin/env python3
r"""
Regenerate the LSO tab's CASE I PATTERN drawing (v1.3-beta36, SNAPPED).

A clean stylized horizontal CASE I racetrack with ROUNDED turns; aircraft SNAP
to the fixed pattern points (INITIAL / BREAK / DOWNWIND / ABEAM / 180 / GROOVE /
TRAP) — always reads cleanly (the user preferred this over the live relative
plot).  Boat at the centre with the groove (final, angled deck) into the trap.

Curves are dot strings (rotation-free, like the range rings).  Splices into
carrier-gui.dlg between the "CASE I PATTERN" and "LSO LIGHTS" markers.  The
hook's PATTERN_XY (point -> pixel) must match the POINTS table below.
"""
import math
import re
from pathlib import Path

DLG = Path(r"C:\Users\Fett\Saved Games\Claude Dump\CarrierGUI\Hooks\carrier-gui.dlg")

# ---- racetrack geometry from REAL tacview data (LSO scope x16..524, y48..278)
# v1.3-beta54: sized from the squadron's own CASE I practice (CarrierGUI\
# tacview\, 19 jets, ~4k in-pattern samples): median abeam 1697 m (0.92 nm,
# p75 1.4 nm), upwind past bow median 1176 m, groove from ~1.2-2 km astern
# along the angled-deck final.  Drawn under the SAME ISOTROPIC mapping the
# hook's live plot uses: px = (290 + ahead*0.06, 193 + stbd*0.06).
LEG_X0, LEG_X1 = 170, 368          # ahead -2000 m .. +1300 m at S=0.06
Y_TOP, Y_BOT   = 91, 193           # downwind at stbd -1700 m; upwind over boat
CY = (Y_TOP + Y_BOT) // 2          # 142
R  = (Y_BOT - Y_TOP) // 2          # 51 turn radius
LX, RX = LEG_X0, LEG_X1
BOAT = (290, 193)                  # boat ON the upwind leg (as flown)
GROOVE_TAIL = (200, 179)           # groove entry: ahead -1500 m on the FB line

POINTS = {   # nominal station positions (doc/labels; the live dot flies free)
    'INITIAL':  (210, 216),
    'BREAK':    (RX + R - 6, 116),
    'DOWNWIND': (320, Y_TOP),
    'ABEAM':    (262, Y_TOP),
    '180':      (LX - R + 8, 172),
    'GROOVE':   (218, 186),
    'TRAP':     BOAT,
}

lines = []
def L(s=''): lines.append(s)
def solid(name, x, y, w, h, skin, z): L(f'c.{name} = solidW({x}, {y}, {w}, {h}, {skin}, {z})')
def label(name, text, x, y, w, skin, h): L(f'c.{name} = lbl("{text}", {x}, {y}, {w}, {skin}, {h})')

def arc(prefix, cx, cy, r, a0, a1, gap=13, d=4):
    n = max(2, int(round(math.radians(abs(a1 - a0)) * r / gap)))
    for i in range(n + 1):
        a = math.radians(a0 + (a1 - a0) * i / n)
        solid(f'{prefix}{i+1}', round(cx + r*math.cos(a) - d/2),
              round(cy + r*math.sin(a) - d/2), d, d, 'SCOPE_RG_SKIN', 3)
    return n + 1

L('-- == CASE I PATTERN ==  (generated by Tools/gen_lso_pattern.py)')
L('-- Stylized horizontal CASE I racetrack with rounded turns; jets SNAP to the')
L('-- fixed pattern points (clean read).  Boat at centre, groove into the trap.')
label('lblPatHdr', "CASE I OVERHEAD  ·  port racetrack", 6, 30, 520, 'LabelSkin', 18)
L('')

solid('pScope', 16, 48, 508, 230, 'SCOPE_BG_SKIN', 1)
solid('pBordT', 16,  48, 508, 1, 'SCOPE_RG_SKIN', 3)
solid('pBordB', 16, 278, 508, 1, 'SCOPE_RG_SKIN', 3)
solid('pBordL', 16,  48, 1, 230, 'SCOPE_RG_SKIN', 3)
solid('pBordR', 524, 48, 1, 231, 'SCOPE_RG_SKIN', 3)
L('')

L('-- straight legs: upwind (bottom, starboard) + downwind (top, port)')
solid('pLegB', LEG_X0, Y_BOT - 1, LEG_X1 - LEG_X0, 2, 'SCOPE_RG_SKIN', 3)
solid('pLegT', LEG_X0, Y_TOP - 1, LEG_X1 - LEG_X0, 2, 'SCOPE_RG_SKIN', 3)
L('')

L('-- rounded turns: break (right end) + 180 (left end)')
nR = arc('pArcR', RX, CY, R, -90,  90)    # right half: top -> right -> bottom
nL = arc('pArcL', LX, CY, R,  90, 270)    # left half: bottom -> left -> top
L('')

L('-- groove: final on the angled deck into the trap')
gx0, gy0 = GROOVE_TAIL; gx1, gy1 = BOAT
nG = max(2, int(round(math.hypot(gx1 - gx0, gy1 - gy0) / 13)))
for i in range(nG + 1):
    x = gx0 + (gx1 - gx0) * i / nG
    y = gy0 + (gy1 - gy0) * i / nG
    solid(f'pGrv{i+1}', round(x - 2), round(y - 2), 4, 4, 'SCOPE_RING_SKIN', 3)
nG = nG + 1
L('')

L('-- carrier marker (nose right along the BRC) — hull + bow nub')
solid('pShip',    BOAT[0] - 30, BOAT[1] - 8, 60, 16, 'SHIP_MARK_SKIN', 4)
solid('pShipBow', BOAT[0] + 30, BOAT[1] - 4, 10,  8, 'SHIP_MARK_SKIN', 4)
L('')

L('-- pattern-point labels')
LBL = {
    'lblPatInitial': ('INITIAL',  POINTS['INITIAL'][0] - 30, POINTS['INITIAL'][1] + 6, 'DeckSkin'),
    'lblPatBreak':   ('BREAK',    POINTS['BREAK'][0] - 56,   POINTS['BREAK'][1] - 4,   'DeckSkin'),
    'lblPatDwnwd':   ('DOWNWIND', POINTS['DOWNWIND'][0] + 6, POINTS['DOWNWIND'][1] - 20,'DeckSkin'),
    'lblPatAbeam':   ('ABEAM',    POINTS['ABEAM'][0] - 56,   POINTS['ABEAM'][1] - 20,  'DeckSkin'),
    'lblPat180':     ('180',      POINTS['180'][0] - 34,     POINTS['180'][1] - 6,     'DeckSkin'),
    'lblPat90':      ('90',       LX + 8,                    140,                      'DeckSkin'),
    'lblPatGroove':  ('GROOVE',   POINTS['GROOVE'][0] - 60,  POINTS['GROOVE'][1] - 4,  'DeckSkin'),
    'lblPatTrap':    ('TRAP',     POINTS['TRAP'][0] + 36,    POINTS['TRAP'][1] - 8,    'DeckHdr'),
    'lblPatCv':      ('CV',       POINTS['TRAP'][0] - 8,     POINTS['TRAP'][1] - 8,    'CarrierMark'),
}
for nm, (t, x, y, sk) in LBL.items():
    label(nm, t, x, y, 70, sk, 14)
L('')

L('-- aircraft pool (hook snaps each to its classified point)')
L('for i = 1, 8 do')
L('    c["acftDot" .. i] = solidW(-300, -300, 5, 5, CONTACT_SKIN, 4)')
L('    c["acftPat" .. i] = lbl("", -300, -300, 80, SpotSkin, 13)')
L('end')
L('')

new_section = '\n'.join(lines) + '\n'
src = DLG.read_text(encoding='utf-8')
a = re.search(r'-- ?[─=-]+ ?CASE I PATTERN[^\n]*\n', src)
b = re.search(r'-- ?[─=-]+ ?LSO LIGHTS', src)
assert a and b, 'CASE I PATTERN / LSO LIGHTS markers not found'
src = src[:a.start()] + new_section + '\n' + src[b.start():]
DLG.write_text(src, encoding='utf-8')
print(f"LSO pattern (snapped) regenerated. arcs L={nL} R={nR}, groove={nG}")
print("PATTERN_XY for the hook:")
for k, v in POINTS.items():
    print(f"  {k:9s} = {{ {v[0]}, {v[1]} }},")
