#!/usr/bin/env python3
r"""
Regenerate the ENTIRE TOWER-tab section of carrier-gui.dlg (v1.3-beta31).

The TOWER tab is the CASE I marshal-stack manager.  Layout, top -> bottom:

  1. OVERHEAD CIRCLE (left) — a 5 nm CASE I overhead holding pattern drawn as a
     schematic.  The boat sits on the FAR-RIGHT edge of the circle (= point 1);
     going counter-clockwise the cardinal points are 2 (top), 3 (left), 4
     (bottom).  Aircraft are plotted by their deck-frame position from the ship
     so they orbit this ring.  The display does NOT rotate: it is a fixed
     schematic with the boat always on the right, screen-up = the ship's
     final-bearing (deck) axis.
  2. SIDE-VIEW altitude ladder (right) — the angels stack, 2k .. 10k ft.
  3. STACK / CHARLIE'D / COMMENCING bordered tables — same grid styling as the
     MARSHALL assignment table.  Click any row in STACK to give that jet a
     Charlie (panel-only); it hops to the CHARLIE'D table.  When a Charlie'd
     jet reaches point 3 it auto-moves to COMMENCING.  Click a CHARLIE'D row to
     undo.

This splices between the "= TOWER TAB =" and "= MARSHALL TAB =" banner comments,
replacing whatever is there.  Re-runnable.

Geometry knobs are all at the top so the orientation / scale can be retuned in
one place.
"""
import math
from pathlib import Path

DLG = Path(r"C:\Users\Fett\Saved Games\Claude Dump\CarrierGUI\Hooks\carrier-gui.dlg")

# ----------------------------------------------------------------- geometry --
W = 540
PAD = 6

# Overhead circle scope (left).
SX, SY, SW, SH = 14, 44, 258, 258
CX = SX + SW // 2            # 143
CY = SY + SH // 2            # 173
RR = 116                     # drawn ring radius (px)
PATTERN_NM = 5               # the holding circle radius the ring represents

# Side-view altitude ladder (right).
VX, VY, VW, VH = 280, 44, 246, 258
SV_TOP, SV_BOT = VY + 12, VY + VH - 12   # 56 .. 290  (10k .. 2k)

# Tables span the full panel width below the radars.
TBL_X = 14
TBL_W = W - 2 * TBL_X        # 512
# column dividers (screen x) and the per-column caption box (x, w)
COL_DIV = [120, 200, 270, 420]
COL = [  # (label, caption_x, caption_w)
    ('MODEX',  20, 96),
    ('ALT',   124, 72),
    ('GS',    204, 62),
    ('POINT', 274, 142),
    ('IN-STK',424,  52),
]
ROW_H = 20
# per-row action button (STACK = give Charlie, CHARLIE'D = undo)
BTN_X, BTN_W, BTN_H = 480, 40, 18

lines = []
ring_dot_count = 0


def L(s=''):
    lines.append(s)


def solid(name, x, y, w, h, skin, z):
    L(f'c.{name} = solidW({x}, {y}, {w}, {h}, {skin}, {z})')


def label(name, text, x, y, w, skin, h):
    L(f'c.{name} = lbl("{text}", {x}, {y}, {w}, {skin}, {h})')


# ------------------------------------------------------------------ header ---
L('-- ================================================================= TOWER TAB ==')
L('-- v1.3-beta31: CASE I marshal-stack manager.  Generated by Tools/gen_tower_stack.py.')
L('--   overhead 5 nm circle (boat on the RIGHT edge = pt 1; CCW 2=top 3=left 4=bottom)')
L('--   + side-view angels ladder + STACK / CHARLIE\'D / COMMENCING bordered tables.')
L('--   Click a STACK row to Charlie it (panel only); pt-3 crossing auto-commences.')
L('')
label('lblTwrOhHdr', "MARSHAL STACK  ·  CASE I overhead  ·  5 nm",
      PAD, 24, 300, 'CapSkin', 14)
L('')

# --- overhead circle scope ---------------------------------------------------
L('-- overhead circle scope (boat on the far-right edge)')
solid('tcBg', SX, SY, SW, SH, 'SCOPE_BG_SKIN', 1)
solid('tcBT', SX, SY, SW, 1, 'SCOPE_RG_SKIN', 3)
solid('tcBB', SX, SY + SH, SW, 1, 'SCOPE_RG_SKIN', 3)
solid('tcBL', SX, SY, 1, SH, 'SCOPE_RG_SKIN', 3)
solid('tcBR', SX + SW, SY, 1, SH, 'SCOPE_RG_SKIN', 3)
# faint axes through the circle centre
solid('tcAxH', SX + 8, CY, SW - 16, 1, 'SCOPE_LN_SKIN', 2)
solid('tcAxV', CX, SY + 8, 1, SH - 16, 'SCOPE_LN_SKIN', 2)
L('')

# ring dots (the 5 nm circle)
L('-- 5 nm holding ring (solid dots)')
gap = 14
n = max(8, int(round(2 * math.pi * RR / gap)))
ring_dot_count = n
for i in range(n):
    th = 2 * math.pi * i / n
    px = CX + RR * math.cos(th)
    py = CY + RR * math.sin(th)
    solid(f'tcRing{i + 1}', round(px - 2), round(py - 2), 4, 4, 'SCOPE_RING_SKIN', 3)
L('')

# four cardinal points: 1=right(boat) 2=top 3=left 4=bottom
pts = {
    1: (CX + RR, CY),   # boat / right
    2: (CX, CY - RR),   # top
    3: (CX - RR, CY),   # left
    4: (CX, CY + RR),   # bottom
}
# number-label offsets nudged toward the circle centre so they sit inside
lbl_off = {1: (-20, -16), 2: (6, 6), 3: (8, -16), 4: (6, -18)}
L('-- cardinal point markers + numbers (1 = boat, CCW)')
for k in (2, 3, 4):                      # pt1 is the ship marker itself
    px, py = pts[k]
    solid(f'tcPt{k}', round(px - 4), round(py - 4), 8, 8, 'SCOPE_RING_SKIN', 3)
for k in (1, 2, 3, 4):
    px, py = pts[k]
    ox, oy = lbl_off[k]
    label(f'tcPtN{k}', str(k), round(px + ox), round(py + oy), 16, 'SpotSkin', 14)
# ship marker sits on point 1 (right edge)
bx, by = pts[1]
solid('tcShip', round(bx - 5), round(by - 5), 10, 10, 'SHIP_MARK_SKIN', 4)
L('')

# contact blip + datablock pools (positioned by the hook each poll)
L('-- contact blips + datablocks (hook repositions every poll)')
for i in range(1, 13):
    solid(f'tcDot{i}', -300, -300, 5, 5, 'CONTACT_SKIN', 4)
    label(f'tcLbl{i}', "", -300, -300, 64, 'SpotSkin', 13)
L('')

# --- side-view altitude ladder ----------------------------------------------
L('-- side-view angels ladder (2 .. 10 k ft)')
label('lblTwrSvHdr', "ANGELS  ·  2 → 10 k ft", VX, 24, 240, 'CapSkin', 14)
solid('tcSvBg', VX, VY, VW, VH, 'SCOPE_BG_SKIN', 1)
solid('tcSvBT', VX, VY, VW, 1, 'SCOPE_RG_SKIN', 3)
solid('tcSvBB', VX, VY + VH, VW, 1, 'SCOPE_RG_SKIN', 3)
solid('tcSvBL', VX, VY, 1, VH, 'SCOPE_RG_SKIN', 3)
solid('tcSvBR', VX + VW, VY, 1, VH, 'SCOPE_RG_SKIN', 3)
# 9 gridlines + labels: 1k increments, 10k (top) down to 2k (bottom)
alt_labels = ['10k', ' 9k', ' 8k', ' 7k', ' 6k', ' 5k', ' 4k', ' 3k', ' 2k']
for gi in range(9):
    gy = round(SV_TOP + (SV_BOT - SV_TOP) * gi / 8)
    solid(f'tcSvG{gi + 1}', VX + 34, gy, VW - 44, 1, 'SCOPE_LN_SKIN', 2)
    label(f'tcSvA{gi + 1}', alt_labels[gi], VX + 6, gy - 7, 26, 'RadarLbl', 12)
# modex slot pool
for i in range(1, 11):
    label(f'tcSv{i}', "", -200, -200, 44, 'SpotSkin', 14)
L('')


# --- bordered tables ---------------------------------------------------------
def build_table(prefix, hdr_text, top_y, n_rows, btn_text=None):
    """Emit a bordered table; return the y just below it.

    btn_text — if set, emit a real Button per row at the right edge (Static
    cells don't reliably fire click callbacks in this dxgui; Buttons do).
    """
    L(f'-- {hdr_text} table')
    label(f'{prefix}Hdr', hdr_text, TBL_X, top_y, TBL_W, 'LabelSkin', 18)
    box_top = top_y + 20
    cap_y = box_top + 2
    sep_y = box_top + 17
    rows_y0 = sep_y + 2
    box_bot = rows_y0 + n_rows * ROW_H
    # border box
    solid(f'{prefix}BT', TBL_X, box_top, TBL_W, 1, 'SCOPE_RG_SKIN', 3)
    solid(f'{prefix}BB', TBL_X, box_bot, TBL_W, 1, 'SCOPE_RG_SKIN', 3)
    solid(f'{prefix}BL', TBL_X, box_top, 1, box_bot - box_top, 'SCOPE_RG_SKIN', 3)
    solid(f'{prefix}BR', TBL_X + TBL_W, box_top, 1, box_bot - box_top, 'SCOPE_RG_SKIN', 3)
    solid(f'{prefix}Sep', TBL_X, sep_y, TBL_W, 1, 'SCOPE_RG_SKIN', 3)
    # column dividers
    for di, dx in enumerate(COL_DIV, start=1):
        solid(f'{prefix}V{di}', dx, box_top, 1, box_bot - box_top, 'SCOPE_LN_SKIN', 2)
    # header captions
    for ci, (cap, cxp, cwp) in enumerate(COL, start=1):
        label(f'{prefix}H{ci}', cap, cxp, cap_y, cwp, 'CapSkin', 14)
    # cells (+ optional per-row action button)
    for r in range(1, n_rows + 1):
        ry = rows_y0 + (r - 1) * ROW_H + 1
        for ci, (cap, cxp, cwp) in enumerate(COL, start=1):
            label(f'{prefix}Cell{r}_{ci}', "", cxp, ry, cwp, 'RowSkinMon', 15)
        if btn_text:
            L(f'c.{prefix}Btn{r} = btn("{btn_text}", {BTN_X}, {ry - 2}, {BTN_W})')
            L(f'c.{prefix}Btn{r}.params.bounds.h = {BTN_H}')
    L('')
    return box_bot


y = 312
y = build_table('ts', "STACK  ·  holding   (C = give Charlie)", y, 8, btn_text="C") + 8
y = build_table('td', "CHARLIE'D  ·  cleared   (U = undo)", y, 5, btn_text="U") + 8
y = build_table('tm', "COMMENCING  ·  past point 3", y, 5) + 8

L('')

# ----------------------------------------------------------------- splice ----
new_section = '\n'.join(lines) + '\n'

src = DLG.read_text(encoding='utf-8')
start_marker = '-- ================================================================= TOWER TAB =='
end_marker = '-- ============================================================== MARSHALL TAB =='
i0 = src.index(start_marker)
i1 = src.index(end_marker)
src = src[:i0] + new_section + '\n' + src[i1:]
DLG.write_text(src, encoding='utf-8')

print(f"TOWER section regenerated: {len(lines)} lines, ring dots = {ring_dot_count}")
print(f"  STACK rows 8, CHARLIE'D rows 5, COMMENCING rows 5; tables end at y={y}")
