#!/usr/bin/env python3
"""One-shot splice for v1.3-beta10: horizontal LSO/DECKBOSS + finer rings."""
from pathlib import Path
import re

p = Path(r"C:\Users\Fett\Saved Games\Claude Dump\CarrierGUI\Hooks\carrier-gui.dlg")
src = p.read_text(encoding='utf-8')
geom = Path(__file__).with_name('radar_geom.txt').read_text(encoding='utf-8')

def section(name):
    lines, grab = [], False
    for ln in geom.split('\n'):
        if ln.startswith('--'):
            grab = name in ln
            continue
        if grab and ln.strip():
            lines.append(ln)
    return '\n'.join(lines)

m_rings = (section('MARSHALL CCZ rings')
           + '\n\n-- bearing ticks every 30 deg just outside the 60 nm ring\n'
           + section('bearing ticks'))
t_rings = section('TOWER stack scope')
l_arc   = section('LSO horizontal racetrack')

# ---- 1. MARSHALL ring block ----
pat = re.compile(
    r"-- range rings \(generated by Tools/gen_radar_geometry\.py — 20/40/60 nm\)\n"
    r".*?\n\n-- Range scale ticks \+ cardinal letters",
    re.S)
new = ("-- range rings + bearing ticks (generated by Tools/gen_radar_geometry.py)\n"
       + m_rings + "\n\n-- Range scale ticks + cardinal letters")
src, n = pat.subn(new, src)
assert n == 1, f"marshall rings: {n}"

# ---- 2. TOWER header + rings + centre marker ----
src = src.replace(
    'c.lblTwrOhHdr   = lbl("OVERHEAD  ·  25 nm",            PAD,     30, 250, CapSkin,  14)',
    'c.lblTwrOhHdr   = lbl("MARSHAL STACK  ·  6 nm  ·  centred on stack", PAD, 30, 270, CapSkin, 14)')
pat = re.compile(
    r"-- rings \(generated — 12\.5 / 25 nm\)\n(?:c\.tRing[AB]\d+ +US= seg\([^\n]*\n)+".replace(' +US=', r'\s*='))
pat = re.compile(r"-- rings \(generated — 12\.5 / 25 nm\)\n(?:c\.tRing[AB]\d+\s*=\s*seg\([^\n]*\n)+")
new = "-- stack-relative rings: 2 / 4 / 6 nm (generated)\n" + t_rings + "\n"
src, n = pat.subn(new, src)
assert n == 1, f"tower rings: {n}"
src = src.replace(
    'c.lblTwrOhCv    = lbl("CV",                            136,    104, 24, CarrierMark, 14)',
    'c.lblTwrOhCv    = lbl("STK",                           136,    104, 30, CarrierMark, 12)')

# ---- 3. LSO horizontal racetrack ----
pat = re.compile(
    r"-- racetrack legs\n.*?-- Aircraft slot pool — 8 modex labels",
    re.S)
new_lso = (
"""-- racetrack legs — HORIZONTAL layout (uses the full panel width).
-- Flow: INITIAL enters bottom-left, upwind to the ship at bottom-right,
-- 90° BREAK up the right side, 90° onto the downwind (top leg, right→left),
-- rounded 180 turn on the left, back to the GROOVE and the TRAP.
c.pLegB    = solidW(120, 219, 350,   2, SCOPE_RG_SKIN, 3)
c.pLegR    = solidW(468,  90,   2, 131, SCOPE_RG_SKIN, 3)
c.pLegT    = solidW(120,  89, 350,   2, SCOPE_RG_SKIN, 3)
-- rounded 180 turn on the left (semicircle, generated)
""" + l_arc + """
-- own ship on the bottom leg (trap end)
c.pShip    = solidW(424, 209,  22,  12, SHIP_MARK_SKIN, 3)

-- Pattern landmark labels (sit just off the drawn track)
c.lblPatInitial  = lbl("INITIAL",   110, 230, 70, DeckSkin, 14)
c.lblPatBreak    = lbl("BREAK",     478, 148, 60, DeckSkin, 14)
c.lblPatDwnwd    = lbl("DOWNWIND",  240,  68, 80, DeckSkin, 14)
c.lblPatAbeam    = lbl("ABEAM",     408,  68, 60, DeckSkin, 14)
c.lblPat180      = lbl("180",        38, 148, 40, DeckSkin, 14)
c.lblPat90       = lbl("90",         88, 238, 30, DeckSkin, 14)
c.lblPatGroove   = lbl("GROOVE",    320, 230, 70, DeckSkin, 14)
c.lblPatTrap     = lbl("TRAP",      424, 192, 50, DeckHdr,  14)
c.lblPatCv       = lbl("CV",        450, 230, 30, CarrierMark, 14)

-- Aircraft slot pool — 8 modex labels""")
src, n = pat.subn(new_lso, src)
assert n == 1, f"lso racetrack: {n}"

# ---- 4. DECKBOSS horizontal silhouette ----
pat = re.compile(
    r"-- ── deck silhouette drawn with solid fills \+ edge lines ─+\n"
    r".*?c\.dbEl4 += solidW\([^\n]*\n",
    re.S)
new_deck = """-- ── deck silhouette — HORIZONTAL: BOW = right, PORT = top ────────────────
-- Deck plate x=60..480 (420 long), y=120..240 (120 wide).
c.dbDeck    = solidW( 60, 120, 420, 120, DECK_FILL_SKIN, 1)
-- angled landing-area strip (rises to port/top toward the bow)
do
    local strip = solidW( 75, 161, 270,  48, DECK_STRP_SKIN, 2)
    strip.params.angle = -10
    strip.params.pivotPoint = { ["x"] = 135, ["y"] = 24 }
    c.dbStrip = strip
end
-- deck edge lines
c.dbEdgeT   = solidW( 60, 120, 420,   2, DECK_EDGE_SKIN, 3)
c.dbEdgeB   = solidW( 60, 238, 420,   2, DECK_EDGE_SKIN, 3)
c.dbEdgeL   = solidW( 60, 120,   2, 120, DECK_EDGE_SKIN, 3)
c.dbEdgeR   = solidW(478, 120,   2, 120, DECK_EDGE_SKIN, 3)
-- catapult tracks: 1+2 at the bow (right end), 3+4 angled on the waist
c.dbCat1    = solidW(390, 148,  76,   3, CAT_SKIN, 3)
c.dbCat2    = solidW(390, 184,  76,   3, CAT_SKIN, 3)
do
    local c3 = solidW(160, 172,  76,   3, CAT_SKIN, 3)
    c3.params.angle = -10
    c3.params.pivotPoint = { ["x"] = 38, ["y"] = 1 }
    c.dbCat3 = c3
    local c4 = solidW(160, 202,  76,   3, CAT_SKIN, 3)
    c4.params.angle = -10
    c4.params.pivotPoint = { ["x"] = 38, ["y"] = 1 }
    c.dbCat4 = c4
end
-- island on the starboard (bottom) edge + the four elevators
c.dbIslandF = solidW(290, 224,  64,  14, ISLAND_SKIN, 2)
c.dbEl1     = solidW(368, 230,  30,  10, ELEV_SKIN, 2)
c.dbEl2     = solidW(240, 230,  30,  10, ELEV_SKIN, 2)
c.dbEl3     = solidW(150, 122,  30,  10, ELEV_SKIN, 2)
c.dbEl4     = solidW( 90, 230,  30,  10, ELEV_SKIN, 2)
"""
src, n = pat.subn(new_deck, src)
assert n == 1, f"deck silhouette: {n}"

# ---- 5. DECKBOSS zone labels ----
pat = re.compile(
    r"-- Deck zone labels — positioned on the drawn silhouette.*?"
    r"c\.lblDbStern += lbl\([^\n]*\n",
    re.S)
new_labels = """-- Deck zone labels — horizontal silhouette (BOW right, PORT top)
c.lblDbBow      = lbl("BOW",        484, 172, 40, DeckSkin, 14)
c.lblDbStern    = lbl("STERN",       14, 172, 50, DeckSkin, 14)
c.lblDbCat1     = lbl("CAT1",       392, 132, 44, DeckHdr,  13)
c.lblDbCat2     = lbl("CAT2",       392, 192, 44, DeckHdr,  13)
c.lblDbCat3     = lbl("CAT3",       150, 156, 44, DeckHdr,  13)
c.lblDbCat4     = lbl("CAT4",       150, 208, 44, DeckHdr,  13)
c.lblDbIsland   = lbl("ISLAND",     300, 246, 50, DeckSkin, 12)
c.lblDb6pk      = lbl("6-PACK",     330, 128, 60, DeckSkin, 12)
c.lblDbWaist    = lbl("WAIST",      230, 146, 60, DeckSkin, 12)
c.lblDbElev1    = lbl("EL1",        372, 246, 30, DeckSkin, 11)
c.lblDbElev2    = lbl("EL2",        244, 246, 30, DeckSkin, 11)
c.lblDbElev3    = lbl("EL3",        154, 106, 30, DeckSkin, 11)
c.lblDbElev4    = lbl("EL4",         94, 246, 30, DeckSkin, 11)
c.lblDbJunk     = lbl("JUNKYARD",    70, 128, 80, DeckHdr,  12)
"""
src, n = pat.subn(new_labels, src)
assert n == 1, f"deck labels: {n}"

# ---- 6. ON DECK list + conga reposition ----
src = src.replace(
    'c.lblDbOnDeckHdr  = lbl("ON DECK",                                  PAD, 380, W - PAD*2, LabelSkin, 18)',
    'c.lblDbOnDeckHdr  = lbl("ON DECK",                                  PAD, 280, W - PAD*2, LabelSkin, 18)')
src = src.replace(
    'c.lblDbOnDeckCols = lbl("  MODEX     ALONG       ACROSS     ZONE",  PAD, 400, W - PAD*2, CapSkin,   14)',
    'c.lblDbOnDeckCols = lbl("  MODEX     ALONG       ACROSS     ZONE",  PAD, 300, W - PAD*2, CapSkin,   14)')
src = src.replace(
    'c["rowDbOnDeck" .. i] = lbl("", PAD, 418 + (i-1)*15, W - PAD*2, RowSkinMon, 15)',
    'c["rowDbOnDeck" .. i] = lbl("", PAD, 318 + (i-1)*15, W - PAD*2, RowSkinMon, 15)')
src = src.replace(
    'c.lblDbCongaState = lbl("CONGA LINE:  OFF", PAD,        490, 200, ValueSkin, 20)',
    'c.lblDbCongaState = lbl("CONGA LINE:  OFF", PAD,        490, 200, ValueSkin, 20)')  # no-op guard
src = src.replace(
    'c.lblDbCongaState = lbl("CONGA LINE:  OFF", PAD,        600, 200, ValueSkin, 20)',
    'c.lblDbCongaState = lbl("CONGA LINE:  OFF", PAD,        490, 200, ValueSkin, 20)')
src = src.replace(
    'c.btnDbConga      = btn("TOGGLE CONGA",     PAD + 220,  600, 150)',
    'c.btnDbConga      = btn("TOGGLE CONGA",     PAD + 220,  490, 150)')
src = src.replace(
    "PAD, 628, W - PAD*2, CapSkin, 16)",
    "PAD, 518, W - PAD*2, CapSkin, 16)")

p.write_text(src, encoding='utf-8')
print("dlg surgery complete")
